### PR TITLE
Resolves #133 Rename shutdown to descriptor_shutdown

### LINKED ISSUE #133: azmq fails to compile with boost 1.66 due to changes in asio
Hi,

Just tried upgrading my project which uses azmq to user boost 1.66 and there are some breaking changes in the asio library:

```cpp
In file included from /Users/foo/distrib/include/azmq/context.hpp:12:
/Users/foo/distrib/include/azmq/detail/socket_service.hpp:328:35: error: 'azmq::detail::socket_service::shutdown' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
        boost::system::error_code shutdown(implementation_type & impl,
                                  ^
/Users/foo/distrib/include/boost/asio/io_context.hpp:800:32: note: hidden overloaded virtual function 'boost::asio::io_context::service::shutdown' declared here: different number
      of parameters (0 vs 3)
  BOOST_ASIO_DECL virtual void shutdown();
                               ^
/Users/foo/distrib/include/azmq/socket.hpp:109:35: error: use of undeclared identifier 'implementation'
        if (get_service().do_open(implementation, type, optimize_single_threaded, ec))
                                  ^
/Users/foo/distrib/include/azmq/socket.hpp:115:38: error: use of undeclared identifier 'implementation'
        get_service().move_construct(implementation,
                                     ^
/Users/foo/distrib/include/azmq/socket.hpp:117:44: error: no member named 'implementation' in 'azmq::socket'
                                     other.implementation);
                                     ~~~~~ ^
/Users/foo/distrib/include/azmq/socket.hpp:121:35: error: use of undeclared identifier 'implementation'
        get_service().move_assign(implementation,
                                  ^
/Users/foo/distrib/include/azmq/socket.hpp:123:39: error: no member named 'implementation' in 'azmq::socket'
                                  rhs.implementation);
                                  ~~~ ^
```

Also, on a side note, it would be great if you could more regularly version (using a tag) the azmq library so a specific code level can more easily be recoverable from github.

Thanks for the library and all the effort you've put into it.

O.

### PR DESCRIPTION
**Pull request by rodgert**
Avoids name collisions in Boost Asio 1.66+

### CODE REVIEW

**Comment by rodgert** [comment]
tagged as v1.0.2
